name: Deploy

on:
  push:
    branches:
      - main
      - Adam

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync Repository
        run: |
          ssh -i /path/to/${{secrets.SSH_PRIVATE_KEY}} ubuntu@ec2-13-232-176-224.ap-south-1.compute.amazonaws.com "cd /srv/strapi && git pull origin main && npm install && pm2 restart all"

